[project]
name = "leclerc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiostream>=0.6.4",
    "elasticsearch[async]>=8.18.0,<9.0.0",
    "kuzu>=0.9.0",
    "polars>=1.29.0",
    "pyarrow>=20.0.0",
]
